# Generated by Django 4.2 on 2023-05-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0003_namedentity_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=0)),
                ('topic', models.CharField(max_length=255)),
            ],
        ),
    ]
